import React from "react";
import { useFetchData } from "../data";

function Dog() {
  // State variables to hold the fetched dog image data and loading status
  const {
    data: dogImage,
    loading,
    error,
    fetchData: fetchImage,
  } = useFetchData("https://dog.ceo/api/breeds/image/random");

  // Function to handle the "Refresh" button click
  const handleRefresh = () => {
    // Call the fetchDogImage function to get a new dog image

    fetchImage();
  };
  return (
    <main className="flex flex-col bg-slate-200">
      <div className="container mx-auto py-20 max-w-[960px] px-5">
        <h3 className="font-bold text-cyan-950">
          All pictures were generated by AI
        </h3>
        <div className="grid p-4 place-items-center">
          {loading ? (
            <>
              <div className=" custom-loader"></div>
              <p className="mt-6 animate-pulse">loading..</p>
            </>
          ) : error ? (
            <p>Error: {error}</p>
          ) : (
            dogImage && (
              <div className="grid p-4 rounded-md shadow-md  place-items-center bg-sky-700">
                {/* Display the fetched dog image */}
                <img
                  className="rounded h-80 w-80"
                  loading="lazy"
                  src={dogImage.message}
                  alt={dogImage.status}
                />
                {/* "Refresh" button to get a new dog image, this can also work if i just pass "fetchpost inside the onclick {fetchpost}*/}
                <button
                  type="reset"
                  onClick={handleRefresh}
                  className="p-2 mt-3 font-bold transition-colors duration-100 rounded-md ring-2 ring-offset text-slate-300 bg-sky-800 w-max hover:bg-sky-900 active:bg-sky-800"
                >
                  Refresh
                </button>
              </div>
            )
          )}
        </div>
      </div>
    </main>
  );
}

export default Dog;
